apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007  # You can access at localhost:30007
